### ISSUE TITLE
A new problem

### ISSUE THREAD

**Issue by Taylent** [sonal-bansal/Detection-and-Classification-of-Alzheimer-s-Disease#1]
Hello, I need some help.
What format should resize.ipynb and resize data.ipynb read in?
What should I do with the data if I'm going to run train.py?
Thank you first!

**Comment by sonal-bansal** [comment]
@Taylent , Sorry for such a late response. You would a grey scaled image of 260*260 size before running the code.

**Comment by thecheesybit** [comment]
can you please link any email or phone no. or if you could contact me  { ak818ace@gmail.com } I am working on a research paper regarding the same topic I needed few answers if you could help me out here

**Comment by abhishek1705** [comment]
Hey even I am working on a similar project . Can you please help me with how to select the right dataset for this from the ADNI site. It would be a huge help.
Thank you.
Contact : abhiwa2000@gmail.com

**Comment by YYZ-TJU** [comment]
Hello! I need some your help about the dataset you chose. I am a student who is working on a research report. Since I want to consider your network as the comparison set, I need to receive your acception and more details about this project. But after I run it on my dataset, it does not show a good performance. Thus, I wish I can have your original dataset.  @sonal-bansal THX.

**Comment by YYZ-TJU** [comment]
And my gmail : yyz82619962@gmail.com

**Comment by sonal-bansal** [comment]
Hi @EnvyConsuMe ,
Please reach out to me in bansalsonal51@gmail.com
